name: Branchyng Strategy
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev/*

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@master
      - name: Merge feat and dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: feat/test
          target_branch: dev/test
          github_token: ${{ github.token }}

  createPullRequest:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: sync-branch
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        run:
          curl -X POST -u $GITHUB_TOKEN:x-oauth-basic -H "Accept:application/vnd.github+json" https://api.github.com/repos/bgarrido2314/branching-strategy/pulls -d '{"title":"Dev-Qa","body":"Please pull these new changes in!","head":"dev/test","base":"qa/feat"}'
